print('===== DESAFIO 04 ====')
n = input('Digite algo: ')
print('O tipo é {}'.format(type(n)))
print('Númerico: {}'.format(n.isnumeric()))
print('Alfabético: {}'.format(n.isalpha()))
print('Alfanumérico: {}'.format(n.isalnum()))
print('Decimal: {}'.format(n.isdecimal()))
print('Minúsculo: {}'.format(n.islower()))
print('Maiúsculo: {}'.format(n.isupper()))
print('Numerico: {}'.format(n.isnumeric()))
print('Digito: {}'.format(n.isdigit()))
